### ISSUE TITLE
Post - archivo vacío

### ISSUE THREAD

**Issue by ivanfranco502** [AxelKreitler/GitNetCore#1]
@AxelKreitler, vamos por acá así las consultas las tengo centralizadas dentro de cada repo.
Era lo que te comentaba ayer, sobre tener claro que el cliente tiene un File System propio independiente del Servidor.

El controller en este caso no tiene acceso a ese path donde estás queriendo obtener el archivo (salí del escenario de tu PC local). Un servidor en una VM de Azure de USA no va a tener acceso a tu carpeta C:/Users/Axel/Downloads/imagenEjemplo.png.

Es por esto, que al momento de realizar la acción POST de subida. Tendrías que mandar en forma serializada (para que pueda enviarse a través de un canal de comunicación) el contenido del archivo. ¿Cómo se hace? Hay varias formas, byte[], en base64, etc.

**Comment by AxelKreitler** [comment]
@ivanfranco502 Buenas, he realizado la acción de forma sugerida (guardar de forma serializada), amplié la base de datos con un Byte[] para los posts, actualmente en la base de datos se guarda el Byte[] del archivo subido en la columna Files y en FilePath se guarda el formato para renderizar imagenes de string64 en html + la conversion del byte[] a string64,
nota: el String es muy pesado para MySQL por lo que actualmente debe utilizarse con imágenes chicas, hasta que edite MySQL para aceptar tamaños superiores, o simplemente convierta en la renderizacion de la vista el Byte[] y eliminar el guardado del String64, adjunto 2 imágenes mostrando que funciona, Saludos!

![1](https://user-images.githubusercontent.com/40303944/49787501-a33abe80-fd05-11e8-8d0e-a70a76d4fb58.png) 
![2](https://user-images.githubusercontent.com/40303944/49787513-a9309f80-fd05-11e8-9668-c2957c1230fe.png)

**Comment by ivanfranco502** [comment]
@AxelKreitler buenisimo que lo hayas podido sacar andando. Cuando estés listo para que lo revise, armá el PR. Si llegan a quedar dudas tema commits, abrí un issue y lo manejamos por acá.
